### ISSUE TITLE
Create an entity with link to existing entity by posting JSON

### ISSUE THREAD

**Issue by mjstrasser** [mibo/janos#16]
I am trying to create an entity that links to existing entities by posting JSON. I am not sure if I have the JSON wrong or if there is an issue with Janos/Olingo.

The **OfferedDivision** entity has a 1:1 link with the **Division** entity. Simplified Java sources:

```java
@EdmEntityType(namespace = "TEST")
@EdmEntitySet(name = "Divisions")
public class Division {

  @EdmKey @EdmProperty(name = "DivisionID")
  private String divisionID;

  @EdmProperty(name = "Name")
  private String name;

  // etc.
}
```

```java
@EdmEntityType(namespace = "TEST")
@EdmEntitySet(name = "OfferedDivisions")
public class Division {

  @EdmKey @EdmProperty(name = "DivisionID")
  private String divisionID;
  @EdmKey @EdmProperty(name = "Sequence", type = EdmType.BYTE)
  private Short sequence;

  @EdmNavigationProperty(name = "Division")
  private Division division;

  // etc.
}
```

I have posted a Division entity to /Test.svc/Divisions with:

```json
{
  "DivisionID": "01",
  "Name": "Electricity"
}
```
I now want to post another entity that links to it, at /Test.svc/OfferedDivisions with:

```json
{
  "DivisionID": "01",
  "Sequence": 1,
  "Division": {
    "__metadata": {
      "uri": "Divisions('01')"
    }
  }
}
```

But it doesn't work. The error message includes:

> Caused by: org.apache.olingo.odata2.janos.processor.core.util.AnnotationRuntimeException: Missing source field for related data (sourceStore='org.apache.olingo.odata2.janos.processor.core.data.store.InMemoryDataStore@b67a66', targetStore='org.apache.olingo.odata2.janos.processor.core.data.store.InMemoryDataStore@27a933c9').
	at org.apache.olingo.odata2.janos.processor.core.data.source.AnnotationDataSource.writeRelation(AnnotationDataSource.java:321)
	at org.apache.olingo.odata2.janos.processor.core.DataSourceProcessor.createInlinedEntities(DataSourceProcessor.java:1151)
	at org.apache.olingo.odata2.janos.processor.core.DataSourceProcessor.createEntity(DataSourceProcessor.java:324)

**Comment by mjstrasser** [comment]
I get the same error when trying to create two entities in one post, such as:

```json
{
  "OfferedDivisionID": "01",
  "OfferDetails": "Standard Offer",
  "Division": {
    "DivisionID": "01",
    "Name": "Electricity"
  }
}
```
I think that `AnnotationDataSource.writeRelation` is misusing the information it gets from `AnnotationHelper.getCommonNavigationInfo`. I am trying to understand this code better.

**Comment by mjstrasser** [comment]
The exception only occurs if an entity A has navigation to entity B but the latter does *not* have a 1-to-many navigation back to entity A.

In my example, if `Division` class included the following field then I would not see this error:

```java
    @EdmNavigationProperty(name = "OfferedDivisions", toMultiplicity = Multiplicity.MANY)
    private List<OfferedDivision> offeredDivisions = new ArrayList<>();
```

**BUT** one-way links like this are valid in OData and I am copying an existing schema so I can’t add extra navigation.

**Comment by mjstrasser** [comment]
I have been working on the issue of one-way navigation and have what I believe is a working solution in the [NavigationFixes](https://github.com/mjstrasser/janos/tree/NavigationFixes) branch of my fork of this repo. 

I have re-defined the meaning of `isBiDirectional`. In the code it did not mean two-way navigation as I had supposed, but actually meant one-way navigation from the target class to the source class, in a call to `AnnotationHelper.getCommonNavigationInfo(sourceClass, targetClass)`. In my definition, it means that the source class has a navigation property to the target class **and** the target class has a navigation property back to the source class.

* The document [EntityNavigation.md](https://github.com/mjstrasser/janos/blob/NavigationFixes/EntityNavigation.md) illustrates these meanings and how the `AnnotatedNavInfo` class now behaves.

* The unit-test class [AnnotationHelperTest](https://github.com/mjstrasser/janos/blob/NavigationFixes/janos-core/src/test/java/org/apache/olingo/odata2/janos/processor/core/util/AnnotationHelperTest.java) includes tests that show this behaviour.

**Comment by mibo** [comment]
Hi @mjstrasser,

Thanks a lot for the whole work (investigation and fix) around this issue.
If it is okay for you I will squash and merge it into the master branch.
Otherwise if you have any objections please let me know.

Thanks, mibo

**Comment by mjstrasser** [comment]
Hi @mibo 

Please go ahead with your merge. My work has taken me in other directions over the past year and I am quite out of touch with OData now. 

I am pleased my efforts have been useful.

Cheers
Michael
